name: Test
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'site/**'
      - 'netlify.toml'
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'site/**'
      - 'netlify.toml'

env:
  GO_VERSION: "1.22"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.platform.arch }}, ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - os: ubuntu-22.04
          arch: amd64
        - os: macos-15
          arch: arm64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: make test go_test_options='-timeout 20m -race -short'

      - name: "Generate coverage report"
        if: runner.os == 'Linux'
        run: make coverage

  test_tinygo:
    name: "TinyGo build check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: "0.40.1"
      - run: tinygo build ./cmd/wazero
